package 객체지향14;

import java.io.IOException;

public class Q2{
	 public static void main(String[] args) {
         sub();
   }
   public static void sub() {
          int[] array = new int[10];
          try {
        	  int i = array[10];
        	  System.out.println("?! 오류 발생!");
          }catch(ArrayIndexOutOfBoundsException a) {
        	  System.out.println("오류를 잡아보아요~");
        	  
          }
   }

}